spring:
  application:
    name: admin-server
  profiles:
    active:
    - insecure

eureka:
  instance:
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  servlet:
    context-path: /${spring.application.name}
  port: 9099

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: admin
      password: admin

# 注册给eureka的时候告诉eureka自己的密码
eureka:
  instance:
    metadata-map:
      "user.name": ${spring.security.user.name}
      "user.password": ${spring.security.user.password}